language: python
python:
  - "2.6"
  - "2.7"
  - "2.5"
  - "2.6"
  - "2.7"
  - "3"
  - "3.2"
  - "3.3"
#  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: run_tests
